#
# Blog Settings
#
author: Paolo Nicodemo
description: Bazooka
url: http://bazookadeploy.github.io/Bazooka/
title: Bazooka

# Google Analytics
google_analytics_tracking_id: UA-41937157-2

disqus_short_name: bazooka

#
# Jekyll Settings
#
markdown: rdiscount
pygments: true
permalink: /:title/
rdiscount:
  extensions: [smart]
