#
# Blog Settings
#
author: Paolo Nicodemo
description: Bazooka
url: http://bjornej.github.io/Bazooka
title: Bazooka

# Github repositories
github_user: bjornej
github_repo_url: https://github.com/bjornej/


# Disqus Comments
disqus_short_name: bjornej
disqus_show_comment_count: false

# Google Analytics
google_analytics_tracking_id: UA-41937157-2


#
# Jekyll Settings
#
markdown: rdiscount
pygments: true
permalink: /:title/
rdiscount:
  extensions: [smart]

